### PR TITLE
support arrow keys in Configure window

### PR DESCRIPTION
**Pull request by sunaku**
Hello,

Please add support for arrow keys (mainly up & down) in the Configure window.

Currently, those keys close the Configure window and insert an alphabet into my buffer.

Thanks for your consideration (and for a *fantastic* Vim plugin!) :v:

### CODE REVIEW

**Comment by sunaku** [comment]
Hey @epeli Any chance of merging this? :sweat_smile: It removes ESC shortcut for `:hide` so that arrow keys work. :rocket:

**Comment by slashfoo** [comment]
This works, I'll also work on having this enabled with an option and adding it to #45 if it's ok with you guys.

**Comment by sunaku** [comment]
@slashfoo I'm wary of giant patches and pull requests in general, but proceed if you must. :cold_sweat:

**Comment by slashfoo** [comment]
@sunaku I'll merge my branch and if it fails, I'll work it out, it shouldn't break anything, except that the mapping is dd vs d in the pane selection; which I'll address this on my next commit.

would you be able to help me go through and test?

**Comment by slashfoo** [comment]
and of course, I found a logic error just after merging, I'll open a new PR with the prev changes.

**Comment by slashfoo** [comment]
Ok, re-issued in #47.

**Comment by slashfoo** [comment]
I'll close this pull request now, if there's anything I missed feel free to issue a new one.

**Comment by sunaku** [comment]
:books: For posterity, support for arrow keys can be enabled by setting this flag:

```vim
let g:slimux_enable_close_with_esc = 0
```

**Pull request closed without merging**
